name: irss
channels:
  - conda-forge
  - default
  - chogan
dependencies:
  - python=3.6
  - jupyter
  - numpy=1.14.3
  - scipy=1.1.0
  - matplotlib=2.2.2
  - pandas=0.23.0
  - scikit-learn=0.19.1
  - poliastro=0.11.0
  - h5py
  - mpb
  - pymeep=1.6.0
  - tensorflow-gpu
  - keras
  - pyqt
  - jsoncpp=0.10.6
  - vtk
  - mayavi
